use_frameworks!

platform :ios, '10.0'

target 'TestUpdateTool_Example' do
  pod 'TestUpdateTool', :path => '../'

  target 'TestUpdateTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
